name: FRPC Client
version: 1.0.0
slug: frpc
description: FRP Client (frpc) add-on for Home Assistant. Establish reverse proxy
  connections to FRP servers.
url: https://github.com/acmen0102/linknlink-remote
image: ghcr.io/acmen0102/linknlink-remote-frpc:{arch}
startup: services
boot: auto
init: false
arch:
- aarch64
- amd64
- armv7
options:
  server_addr: ''
  server_port: 7000
  token: ''
  local_ip: 127.0.0.1
  local_port: 22
  remote_port: 6000
  proxy_name: homeassistant_proxy
  protocol: tcp
  log_level: info
  log_max_days: 3
  authentication:
    enabled: false
    account: ''
    password: ''
  third_party:
    enabled: false
    provider: ''
    api_key: ''
    api_secret: ''
schema:
  server_addr: str
  server_port: int(0,65535)
  token: str?
  local_ip: str
  local_port: int(1,65535)
  remote_port: int(1,65535)
  proxy_name: str
  protocol: match(tcp|udp|http|https|stcp|sudp|xtcp)
  log_level: list(trace|debug|info|warn|error)?
  log_max_days: int(1,30)?
  authentication:
    enabled: bool
    account: str?
    password: password?
  third_party:
    enabled: bool
    provider: str?
    api_key: str?
    api_secret: password?
ports: {}
ports_description: {}
